language: java
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
deploy:
  provider: releases
  api_key:
    secure: VOvMBdOObzMioxERmr/ViY8dHDfBcP3DWMDcHRgxUxxpYW/Ic7mbpyIy6NPw/SK2LVJy5uXSadOcInHWkzXlDETsoQTsHtzZUP/56eYc1hJbwXiqyq9LHrNa6No/OoRHsYjNkhXWr/DPZ/4To7f6mGNloKxwsCVCxgChma/ui5/O5NEjOQ1CsVar8+J9Qu3xLBpJZNKAce/I3hvFRoJMGSUmw6C0U71jjzBknVsRqxP6+yYzFNaZyk9U/B4cy6mCaqE8YRtj0Smk3XImrQsutbV3LP7egtzf/Y76MWhnq/2VCUaxDxDHP6ZiMca9/UOCXnBuQt3B26Fh3Pp4kH5/iqxIb17VpfeURDQtSvwM6cKdfhv7OOVUOMRGkZw+Tim9WCEsRfLgy277O7ax/rond1YywKPvR8Mxan1su5zJEA1W9gp2oeWML169ku7liKhsJXcHt9u6Ifx10nuRgB6Ho5x5dDoPgKRu7vhjhSjiQZtrLi9DckL5bwB8It0S1HQYgeFBnQC4NvFDjCzz6KmQ2Zwi1/HEq0nKkl/W25Qih02jyqOK03sQ3y5ZExVOFQo+QWdNed4+KR336Ykusx1cvGoO4t3BSEoHkr7kz7GBfFmYuGt7/wVt39VtfLIfRFGVLUCmWpI2Ioq3Q+R5T60vWx2rAYSHce9hVksLvQ77e6c=
  file: build/libs/rundeck-puppet-classifier-step-plugin-*.jar
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: gschueler/rundeck-puppet-classifier-step-plugin
